apiVersion: v1
kind: ConfigMap
data:
  ack-4.15-kube-1.29-api-removals-in-4.16: |-
      Kubernetes 1.29 and therefore OpenShift 4.16 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/7031404 for details and instructions.
metadata:
  name: admin-gates
  namespace: openshift-config-managed
  annotations:
    kubernetes.io/description: Define update gates for the administrator to acknowledge in the admin-acks ConfigMap in the openshift-config namespace.
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
